### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by HN123-123** [fenglinliu98/MIA#4]
When i run "Test.py", that occured the error "AttributeError: 'CocoEvalLoader' object has no attribute 'samples' " .
How can i fix it???

**Comment by HN123-123** [comment]
The detail information of error as follow:
 
![20200727104033](https://user-images.githubusercontent.com/54923253/88498431-a9260600-cff5-11ea-943c-bf988297953d.jpg)

The version  python2.7, pytorch1.2.0, torchvison0.4.0 for which i used to run the code.

**Comment by fenglinliu98** [comment]
Hi, I'm sorry to cause you trouble, can you successfully train this code?

**Comment by HN123-123** [comment]
Yes, it can train successfully. But fail to test.

**Comment by fenglinliu98** [comment]
Ok, I will try to reproduce and solve your problem later.

**Comment by fenglinliu98** [comment]
The error is caused by the missing of the following code, which is necessary for torchvision0.4.0:

    def __len__(self):
        return len( self.imgs )

I have updated the Test.py. Now, you can use the new Test.py to conduct the inference.

**Comment by HN123-123** [comment]
It can work now, much thanks for you!

**Comment by fenglinliu98** [comment]
You're welcome

**Comment by HN123-123** [comment]
Sorry to bother you again.
I finished training of  VisualAttention and ConceptAttention.
But when i try to train the model of VisualCondition and ConceptCondition , i mat the error that “RuntimeError: input must have 3 dimensions, got 2” in Main.py line 152, "h_t, states = self.LSTM( t_a, states )" and the same as line 157 "h_t, states = self.LSTM( v_a, states )", the detail of error as follow:
![image](https://user-images.githubusercontent.com/54923253/90333185-46bd9580-dff6-11ea-8d72-438eb1331e16.png)

I add "VisualRegionalAttention" to the candidate list in Main.py line 131 "candidate_model = ['VisualAttention', 'ConceptAttention', 'VisualCondition', 'ConceptCondition', 'VisualRegionalAttention']", but when i try  train the VisualRegionalAttention, it occured that "UnboundLocalError: local variable 'attention_input' referenced before assignment" in Main.py line 185. The detail information as follow:
![image](https://user-images.githubusercontent.com/54923253/90333311-4f629b80-dff7-11ea-81a9-e0c947855cc0.png)

**Comment by fenglinliu98** [comment]
Hi, I'm sorry to cause you trouble again. I find that the errors are caused by the following bugs, which have been fixed in the latest Models/Main.py:

```
h_t, states = self.LSTM( t_a.unsqueeze( 1 ), states )
h_t, states = self.LSTM( t_a.unsqueeze( 1 ), states )
```

Now, you can use the new Models/Main.py to conduct the training. All the best.
